name: .NET Core

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.102
    - name: Install dependencies
      run: dotnet restore src/Calabonga.AspNetCore.Controllers.sln
    - name: Build
      run: dotnet build src/Calabonga.AspNetCore.Controllers.sln --configuration Release --no-restore 
    - name: Publish Calabonga.AspNetCore.Controllers
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: src/Calabonga.AspNetCore.Controllers/Calabonga.AspNetCore.Controllers.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
